### ISSUE TITLE
error with hugo serve

### ISSUE THREAD

**Issue by mitch40** [magicsword-io/LOLDrivers#107]
Hi, thank you for this amazing project, i'm trying to build a docker image and i've encountered an error during execution of "hugo serve":

```
(loldrivers-py3.11) root@7f85c1b3f792:/LOLDrivers/loldrivers.io# hugo serve
Start building sites … 
hugo v0.111.3+extended linux/amd64 BuildDate=2023-03-16T08:41:31Z VendorInfo=debian:0.111.3-1
Error: Error building site: "/LOLDrivers/loldrivers.io/content/_index.md:31:1": failed to extract shortcode: template for shortcode "block" not found
Built in 109 ms`
```

Any idea? Thanks

**Comment by josehelps** [comment]
Hey yeah you need the theme, its a git submodule, but you can also grab it from here:
https://github.com/josehelps/compose

**Comment by mitch40** [comment]
Thanks you for your quick answer, i'm not very familiar to deploy this kind of project !
