### ISSUE TITLE
Add Mozglue.dll

### ISSUE THREAD

**Issue by JayP232** [magicsword-io/LOLDrivers#109]
Detected file name: Mozglue.dll
Virus Total link: https://www.virustotal.com/gui/file/fede6e1698ffece6eca17f5b14511e027516b6f15917e624e8cdcfac97657ee2
Virus total results: 22/69 - 

SHA1: 7b35c543bec4e34c34957ca4a7125789b89ba29d
SHA256: fede6e1698ffece6eca17f5b14511e027516b6f15917e624e8cdcfac97657ee2
MD5: 307e74b730405cede8e39c1139f69650

**Comment by MHaggis** [comment]
Hi @JayP232 do you happen to have any more context on this?

**Comment by nasbench** [comment]
@JayP232 any updates on this? To me this looks like a DLL and not a driver. So this doesn't qualify for LOLDrivers.

I'm gonna close this issue for being stale. Feel free to open it again if you have further info to provide.
