### ISSUE TITLE
WDAC Deny Policy not working

### ISSUE THREAD

**Issue by TLG95** [magicsword-io/LOLDrivers#112]
Hi, we have implemented wdac in our organization based on merging allowall.xml policy and blocking policy for a few specific vendors and products.
We encounter a problem on portableapps.com applications: the setups are indeed blocked but if the application is unpacked, it doesn't matter if I block by the publisher, the hash, the path, the file name, etc., the execution is still allowed.
On the other hand, if my policy is based on merging a scan of the workstation with the blocking policy, everything is blocked.
So the problem would come from the allowall policy?

Another problem, the execution of a specific MSP patch is blocked even if the policy applied on the workstation is only allowall

**Comment by josehelps** [comment]
Hey, @TLG95 the project does not provide an official WDAC policy today apologies but I am not sure what you are referring to.
