### ISSUE TITLE
Add mEfEk.sys

### ISSUE THREAD

**Issue by Viralmaniar** [magicsword-io/LOLDrivers#114]
https://news.sophos.com/en-us/2022/12/13/signed-driver-malware-moves-up-the-software-trust-chain/

<html><body>

9b1b15a3aacb0e786a608726c3abfc94968915cedcbd239ddf903c4a54bfcf0c | 2022-07-27 21:05:11 | Zhuhai liancheng Technology Co., Ltd.
-- | -- | --
42b22faa489b5de936db33f12184f6233198bdf851a18264d31210207827ba25 | 2022-08-09 14:07:45 | Windows Hardware Compatibility Publisher
6839fcae985774427c65fe38e773aa96ec451a412caa5354ad9e2b9b54ffe6c1 | 2022-08-21 15:30:50 | Windows Hardware Compatibility Publisher
7f4555a940ce1156c9bcea9a2a0b801f9a5e44ec9400b61b14a7b1a6404ffdf6 | 2022-08-22 15:38:20 | Windows Hardware Compatibility Publisher
d7c81b0f3c14844f6424e8bdd31a128e773cb96cccef6d05cbff473f0ccb9f9c | 2022-09-20 02:36:50 | NVIDIA Corporation
5f6fec8f7890d032461b127332759c88a1b7360aa10c6bd38482572f59d2ba8b | 2022-09-24 06:42:44 | Beijing JoinHope Image Technology Ltd.
0440ef40c46fdd2b5d86e7feef8577a8591de862cfd7928cdbcc8f47b8fa3ffc | 2022-09-30 16:50:19 | Zhuhai liancheng Technology Co., Ltd.
274340f7185a0cc047d82ecfb2cce5bd18764ee558b5227894565c2f9fe9f6ab | 2022-10-21 02:45:30 | Windows Hardware Compatibility Publisher
0d10c4b2f56364b475b60bd2933273c8b1ed2176353e59e65f968c61e93b7d99 | 2022-10-21 02:47:56 | Windows Hardware Compatibility Publisher
c8f9e1ad7b8cce62fba349a00bc168c849d42cfb2ca5b2c6cc4b51d054e0c497 | 2022-10-21 20:45:56 | Windows Hardware Compatibility Publisher
8e035beb02a411f8a9e92d4cf184ad34f52bbd0a81a50c222cdd4706e4e45104 | 2022-10-27 01:19:05 | Windows Hardware Compatibility Publisher

</body>
</html>

**Comment by MHaggis** [comment]
Thank you @Viralmaniar ! We were missing 1. I got it loaded up.
