### ISSUE TITLE
PROCEXP152.dll

### ISSUE THREAD

**Issue by pwnren** [magicsword-io/LOLDrivers#124]
https://tria.ge/230713-kam69afh42/behavioral1#report

**Comment by HumbleRens** [comment]
MD5
082fa0a99e4c564e9361afb33829965d

SHA1
48826c58b3e8e8724026e81d778a39c572a05f04

SHA256
8a2d946f5ef91fff3fe9e4714135a6bf8aee19e1181cf2a34b653dcd714c5604

SHA512
09705ce865c0896bb8be508f4265e9cad679acc23dd1077ba32d29fa47413be2df0a85c2b7c3429f25273cda169d8594ecbf5e6ebf3aa2ae07c72ca3bf725a5f
