### ISSUE TITLE
Add Malicious Driver TfSysMon

### ISSUE THREAD

**Issue by rahulwt** [magicsword-io/LOLDrivers#177]
Hey there,

I came across this https://github.com/BlackSnufkin/BYOVD/tree/main/TfSysMon-Killer, being used by one of the ransomware group to kill EDR service.

Could you add this to the list?
https://www.virustotal.com/gui/file/1c1a4ca2cbac9fe5954763a20aeb82da9b10d028824f42fff071503dcbe15856

**Comment by MHaggis** [comment]
Absolutely! Thank you for contributing!
