### ISSUE TITLE
New Driver Update

### ISSUE THREAD

**Issue by secdev02** [magicsword-io/LOLDrivers#180]
“C-00000291*.sys”

😎 *whistles*

**Comment by secdev02** [comment]
Sourced Here:

https://x.com/patrickwardle/status/1814352433608327208

[ClownStrike.zip](https://github.com/user-attachments/files/16316621/ClownStrike.zip)

Mahalo

**Comment by nasbench** [comment]
now that we know those channel files aren't drivers, and the driver itself can only trigger a bsod with that specific channel, i don't think this classifies for loldrivers anymore. (at least we don't have a category for such drivers yet) cc @MHaggis

**Comment by nasbench** [comment]
Closing this as not possible for now. Maybe we'll add a category for such edge cases if we have enough data.

Thanks all for the disucssion.
