### ISSUE TITLE
samples.sha256 hasn't been updated in over a year

### ISSUE THREAD

**Issue by ibell63** [magicsword-io/LOLDrivers#186]
https://github.com/magicsword-io/LOLDrivers/blob/main/detections/hashes/samples.sha256 hasn't been updated in over a year despite other files in this directory having new hashes added.  This seems like an oversight or an automation not working correctly since it seems to me like this file is supposed to be all of the SHA256 hashes in any category (malicious, vulnerable, or otherwise a sample).

This same issue affects at least 6 other files in this directory (MD5, SHA1, and authentihash summation files)

Please close if this is intentional or I'm misunderstanding the purpose of these files.

**Comment by nasbench** [comment]
Hey @ibell63 

We dropped that naming convention in favor of dedicated hash files depending on the type of the drivers. So those files are actually old and aren't used anymore (will delete them).

Their replacements are in the form `authentihash_samples*`, `samples_malicious.*` and `samples_vulnerable*`.

Hope this clear things up

**Comment by ibell63** [comment]
Thanks, I will use samples_malicious and samples_vulnerable from now on.
