### ISSUE TITLE
bedaisy.sys

### ISSUE THREAD

**Issue by Wack0** [magicsword-io/LOLDrivers#23]
vulnerable versions of the driver can be used to escalate to wintcb PPL, see https://infosec.exchange/@Rairii/109310279380973806

when I was testing, I used the version with SHA256: 2b120de80a5462f8395cfb7153c86dfd44f29f0776ea156ec4a34fa64e5c4797
probably many more versions exist

**Comment by MHaggis** [comment]
Thank you for this. I'll get it added!
