### ISSUE TITLE
Privileges spelled wrong 

### ISSUE THREAD

**Issue by x90e** [magicsword-io/LOLDrivers#24]
When you click on a driver from the home page, the table that lists it's use cases spells the word privileges incorrectly 

![Screenshot_20230406-133011.png](https://user-images.githubusercontent.com/55068151/230464905-6d377d8a-f088-4e52-b630-99da9db0174a.png)

**Comment by josehelps** [comment]
super embarrassed, thank you sharing! Just pushed a change to main: https://github.com/magicsword-io/LOLDrivers/commit/9e885057c4f8a2b938b7415d1c8a3b748ba46f39
