### ISSUE TITLE
Windows Client

### ISSUE THREAD

**Issue by rtfmkiesel** [magicsword-io/LOLDrivers#59]
In addition to your Sigma and Sysmon detection rules, I made [a client](https://github.com/rtfmkiesel/loldrivers-client) that scans the default Windows driver directories (or a specified one), against the checksums of your JSON API. I would appreciate some feedback.

**Comment by MHaggis** [comment]
Thank you for sharing! We will test it out and report back.

**Comment by MHaggis** [comment]
Shared on the release blog - thank you @rtfmkiesel !
