### ISSUE TITLE
ClamAV hashes

### ISSUE THREAD

**Issue by Sanesecurity** [magicsword-io/LOLDrivers#75]
In case this is useful to generate ClamAV hashes:

sigtool > LOLDrivers.hdb --sha256 *.bin

Example will look like:

LOLDrivers.hdb
06508aacb4ed0a1398a2b0da5fa2dbf7da435b56da76fd83c759a50a51c75caf:23744:0067c788e1cb174f008c325ebde56c22.bin

Format:
sha256_hash:filesize:signature_name

**Comment by MHaggis** [comment]
Thank you for this! We may generate this on the fly beginning next release.
