### ISSUE TITLE
Idea: Add information about upgradability of drivers

### ISSUE THREAD

**Issue by hillu** [magicsword-io/LOLDrivers#76]
In large, diverse environments, it is hard for a security team to assess which vulnerable drivers might break production if they are simply blocked or removed.

I just had a discussion with some colleagues and we thought that it would be useful to add information which drivers could be updated automatically to a non-vulnerable version through Windows update mechanisms. Or if the vendor has published a non-vulnerable driver at all.

Apparently, Microsoft has been doing some [work](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/introducing-a-new-deployment-service-for-driver-and-firmware/ba-p/2176942) in this area, but I don't know if there's a useful API that one could query to automatically retrieve that information.

**Comment by MHaggis** [comment]
We've discussed this a few times and it would be possibly be a lot of labor tracking down vendors and their updates. Every environment will be different and we can't accommodate that. This may be a future add, but right now, not something we can sustainably do. Thank you for the comment, really appreciate it.
