### ISSUE TITLE
Add WinTapix Malicious Driver

### ISSUE THREAD

**Issue by goosvorbook** [magicsword-io/LOLDrivers#94]
https://www.fortinet.com/blog/threat-research/wintapix-kernal-driver-middle-east-countries

https://www.virustotal.com/gui/file/8578bff36e3b02cc71495b647db88c67c3c5ca710b5a2bd539148550595d0330/community

https://www.virustotal.com/gui/file/1485c0ed3e875cbdfc6786a5bd26d18ea9d31727deb8df290a1c00c780419a4e

**Comment by MHaggis** [comment]
Thank you @nasbench and @goosvorbook Got them added
