### ISSUE TITLE
Add Blackcat Drivers

### ISSUE THREAD

**Issue by goosvorbook** [magicsword-io/LOLDrivers#95]
https://www.trendmicro.com/en_us/research/23/e/blackcat-ransomware-deploys-new-signed-kernel-driver.html

https://www.virustotal.com/gui/file/56066ed07bad3b5c1474e8fae5ee2543d17d7977369b34450bd0775517e3b25c

https://www.trendmicro.com/content/dam/trendmicro/global/en/research/23/e/blackcat-ransomware-deploys-new-signed-kernel-driver/indicators-blackcat-ransomware-deploys-new-signed-kernel-driver.txt < for some reason doesn't contain all hashes

dkrtk.sys	91568d7a82cc7677f6b13f11bea5c40cf12d281b	Trojan.Win64.VMPROTECT.R002C0RA
https://www.virustotal.com/gui/file/52d5c35325ce701516f8b04380c9fbdb78ec6bcc13b444f758fdb03d545b0677

fgme.sys	0bec69c1b22603e9a385495fbe94700ac36b28e5	Troj.Win32.TRX.XXPE50F13019
ktes.sys	5ed22c0033aed380aa154e672e8db3a2d4c195c4	Troj.Win32.TRX.XXPE50F13019
kt2.sys		cb25a5125fb353496b59b910263209f273f3552d	Troj.Win32.TRX.XXPE50F13019
ktgn.sys	994e3f5dd082f5d82f9cc84108a60d359910ba79	Rootkit.Win64.POORTRY.A

**Comment by MHaggis** [comment]
Thank you @goosvorbook
